import {useEffect,useMemo,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {useLanguage} from '../i18n/LanguageContext'
import {addCommercialLink,loadMedicalDeviceTraceability,searchMedicalDevices} from '../lib/medicalTraceability'
const money=(v,c='SAR')=>v==null||v===''?'—':`${Number(v).toLocaleString()} ${c||'SAR'}`
const dt=v=>v?new Date(v).toLocaleDateString():'—'
export default function MedicalDeviceTraceability(){
 const {lang}=useLanguage(),[params,setParams]=useSearchParams(); const [q,setQ]=useState(''),[rows,setRows]=useState([]),[selected,setSelected]=useState(params.get('asset')||''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({link_type:'purchase_order',reference_number:'',source_table:'',source_id:'',supplier_name:'',amount:'',currency:'SAR',transaction_date:'',notes:''})
 async function runSearch(term=q){setBusy(true);setError('');try{setRows(await searchMedicalDevices(term))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function load(id){if(!id){setData(null);return}setBusy(true);setError('');try{const d=await loadMedicalDeviceTraceability(id);setData(d);setSelected(id);setParams({asset:id})}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{runSearch('')},[]); useEffect(()=>{if(selected)load(selected)},[])
 const asset=data?.asset,totalCommercial=useMemo(()=>data?.commercialLinks?.reduce((s,x)=>s+(Number(x.amount)||0),0)||0,[data])
 async function saveLink(){if(!asset)return;setBusy(true);setError('');try{await addCommercialLink({...form,asset_id:asset.id});setForm(v=>({...v,reference_number:'',source_table:'',source_id:'',supplier_name:'',amount:'',transaction_date:'',notes:''}));await load(asset.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="facility-panel">
  <h1>{lang==='ar'?'جواز وسجل الجهاز الطبي':'Medical Device Passport & Traceability'}</h1>
  <p>{lang==='ar'?'التتبع بالسيريال من الشراء حتى الصيانة والاستبعاد':'Serial-based traceability from procurement through maintenance and retirement'}</p>
  {error&&<div className="bafm-error">{error}</div>}{busy&&<p>{lang==='ar'?'جاري التحميل...':'Loading...'}</p>}
  <div className="facility-panel"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&runSearch()} placeholder={lang==='ar'?'ابحث بالسيريال أو Asset Tag أو الموديل':'Search Serial / Asset Tag / Model'} style={{minWidth:320,flex:1}}/><button className="btn primary" onClick={()=>runSearch()}>{lang==='ar'?'بحث':'Search'}</button></div><div style={{marginTop:10,maxHeight:240,overflow:'auto'}}>{rows.map(a=><button key={a.id} className="btn" style={{display:'block',width:'100%',textAlign:'start',marginBottom:6}} onClick={()=>load(a.id)}><strong>{a.asset_tag||'—'}</strong> · SN: {a.serial_number||'—'} · {a.exact_model||a.model||'—'} · {a.department||a.site_name||'—'}</button>)}</div></div>
  {asset&&<>
   <div className="stats-grid facility-stats"><div className="stat-card"><span>{lang==='ar'?'السيريال':'Serial Number'}</span><strong>{asset.serial_number||'—'}</strong></div><div className="stat-card"><span>Asset Tag</span><strong>{asset.asset_tag||'—'}</strong></div><div className="stat-card"><span>{lang==='ar'?'جواز الجهاز':'Passport'}</span><strong>{data.passport?.passport_code||'—'}</strong></div><div className="stat-card"><span>{lang==='ar'?'إجمالي الروابط المالية':'Linked Financial Total'}</span><strong>{money(totalCommercial,'SAR')}</strong></div></div>
   <div className="facility-panel"><h2>{lang==='ar'?'هوية الجهاز':'Device Identity'}</h2><table className="facility-table"><tbody><tr><th>{lang==='ar'?'النوع':'Type'}</th><td>{lang==='ar'?(data.type?.name_ar||data.type?.name_en):(data.type?.name_en||data.type?.name_ar)}</td><th>{lang==='ar'?'المصنع':'Manufacturer'}</th><td>{data.manufacturer?.name||'—'}</td></tr><tr><th>Model</th><td>{asset.exact_model||asset.model||'—'}</td><th>Serial</th><td>{asset.serial_number||'—'}</td></tr><tr><th>{lang==='ar'?'الموقع/القسم':'Site / Department'}</th><td>{asset.site_name||'—'} / {asset.department||'—'}</td><th>{lang==='ar'?'الضمان':'Warranty'}</th><td>{dt(asset.warranty_end_date)}</td></tr><tr><th>{lang==='ar'?'الحالة':'Status'}</th><td>{asset.operational_status||'—'}</td><th>{lang==='ar'?'المورد':'Supplier'}</th><td>{asset.supplier_name||'—'}</td></tr></tbody></table><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><Link className="btn" to={`/corrective?asset_id=${asset.id}`}>{lang==='ar'?'الصيانة التصحيحية':'Corrective Maintenance'}</Link><Link className="btn" to={`/ppm?asset_id=${asset.id}`}>{lang==='ar'?'الصيانة الوقائية PPM':'Preventive Maintenance'}</Link><Link className="btn" to={`/procurement?asset_id=${asset.id}&serial=${encodeURIComponent(asset.serial_number||'')}`}>{lang==='ar'?'المشتريات':'Procurement'}</Link><Link className="btn" to={`/maintenance-costing?asset_id=${asset.id}`}>{lang==='ar'?'التكاليف':'Maintenance Cost'}</Link></div></div>
   <div className="facility-panel"><h2>{lang==='ar'?'الصيانة والضمان وسجل الحياة':'Maintenance, Warranty & Lifecycle'}</h2><p><strong>PPM:</strong> {data.ppm?.length||0} · <strong>WO:</strong> {data.snapshot?.medical_work_orders?.length||0} · <strong>Warranty:</strong> {data.snapshot?.warranties?.length||0} · <strong>Timeline:</strong> {data.snapshot?.timeline?.length||0}</p><div style={{overflowX:'auto'}}><table className="facility-table"><thead><tr><th>{lang==='ar'?'التاريخ':'Date'}</th><th>{lang==='ar'?'الحدث':'Event'}</th><th>{lang==='ar'?'الحالة':'Status'}</th></tr></thead><tbody>{(data.snapshot?.timeline||[]).map(e=><tr key={e.id||`${e.occurred_at}-${e.event_type}`}><td>{dt(e.occurred_at)}</td><td>{e.event_title||e.event_type}</td><td>{e.event_status||'—'}</td></tr>)}</tbody></table></div></div>
   <div className="facility-panel"><h2>{lang==='ar'?'المشتريات والمالية المرتبطة بالسيريال':'Procurement & Financial Links by Serial'}</h2><div className="med-grid"><label>{lang==='ar'?'النوع':'Type'}<select value={form.link_type} onChange={e=>setForm({...form,link_type:e.target.value})}><option value="purchase_request">Purchase Request</option><option value="purchase_order">Purchase Order</option><option value="goods_receipt">Goods Receipt</option><option value="invoice">Invoice</option><option value="payment">Payment</option><option value="warranty">Warranty</option><option value="maintenance_cost">Maintenance Cost</option><option value="spare_part">Spare Part</option><option value="other">Other</option></select></label><label>{lang==='ar'?'المرجع':'Reference'}<input value={form.reference_number} onChange={e=>setForm({...form,reference_number:e.target.value})}/></label><label>{lang==='ar'?'المورد':'Supplier'}<input value={form.supplier_name} onChange={e=>setForm({...form,supplier_name:e.target.value})}/></label><label>{lang==='ar'?'القيمة':'Amount'}<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>{lang==='ar'?'العملة':'Currency'}<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></label><label>{lang==='ar'?'التاريخ':'Date'}<input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/></label></div><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder={lang==='ar'?'ملاحظات':'Notes'} style={{width:'100%',marginTop:8}}/><button className="btn primary" disabled={busy} onClick={saveLink} style={{marginTop:8}}>{lang==='ar'?'ربط بالسجل والجواز':'Link to Device Record & Passport'}</button><div style={{overflowX:'auto',marginTop:14}}><table className="facility-table"><thead><tr><th>{lang==='ar'?'النوع':'Type'}</th><th>{lang==='ar'?'المرجع':'Reference'}</th><th>{lang==='ar'?'المورد':'Supplier'}</th><th>{lang==='ar'?'القيمة':'Amount'}</th><th>{lang==='ar'?'التاريخ':'Date'}</th></tr></thead><tbody>{(data.commercialLinks||[]).map(x=><tr key={x.id}><td>{x.link_type}</td><td>{x.reference_number||'—'}</td><td>{x.supplier_name||'—'}</td><td>{money(x.amount,x.currency)}</td><td>{dt(x.transaction_date)}</td></tr>)}</tbody></table></div></div>
  </>}
 </section>
}
