import {useState} from 'react'
import {useAuth} from '../context/AuthContext'
import {useLanguage} from '../i18n/LanguageContext'
import {searchMedicalCompanyLibrary,saveMedicalCompanyLibrary,createOrLinkTenantFromLibrary,loadMedicalRelationshipBundle,enrichMedicalCompanyAI} from '../lib/medicalSmartOnboarding'
const blank={id:null,name_ar:'',name_en:'',company_type:'maintenance_company',website:'',registration_no:'',vat_no:'',email:'',phone:'',city:'',address:'',logo_url:'',logo_source:'',specialties:[],source_type:'manual',source_reference:'',confidence:null}
export default function MedicalSmartOnboarding(){
 const {profile}=useAuth(),{lang}=useLanguage();const ar=lang==='ar';const [q,setQ]=useState(''),[results,setResults]=useState([]),[form,setForm]=useState(blank),[tenant,setTenant]=useState(null),[bundle,setBundle]=useState({clients:[],sites:[],assets:[],projects:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('')
 if(!profile?.is_super_admin)return <section className="facility-module"><div className="alert error">{ar?'Super Admin فقط':'Super Admin only'}</div></section>
 const search=async()=>{setError('');if(!q.trim())return setResults([]);try{setResults(await searchMedicalCompanyLibrary(q.trim()))}catch(e){setError(e.message)}}
 const pick=r=>{setForm({...blank,...r,logo_source:r.logo_source||'library'});setOk(ar?'تم تحميل الشركة من المكتبة الطبية':'Loaded from Medical library')}
 const ai=async()=>{const name=(form.name_en||form.name_ar||q).trim();if(!name)return setError(ar?'اكتب اسم الشركة':'Enter company name');setBusy(true);setError('');try{const x=await enrichMedicalCompanyAI(name);setForm(v=>({...v,name_ar:x.name_ar||v.name_ar,name_en:x.name_en||v.name_en||name,website:x.website||v.website,email:x.email||v.email,phone:x.phone||v.phone,city:x.city||v.city,address:x.address||v.address,logo_url:x.logo_url||v.logo_url,logo_source:x.logo_url?'ai_web':v.logo_source,specialties:Array.isArray(x.specialties)?x.specialties:v.specialties,source_type:'ai_web',source_reference:x.source_reference||v.source_reference,confidence:x.confidence??v.confidence}));setOk(ar?'راجع البيانات المقترحة ثم احفظ':'Review AI suggestions then save')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const id=await saveMedicalCompanyLibrary(form);const list=await searchMedicalCompanyLibrary(form.name_en||form.name_ar);setResults(list);const row=list.find(x=>x.id===id)||list[0];if(row)setForm({...blank,...row});setOk(ar?'تم الحفظ وظهر التحديث مباشرة':'Saved and refreshed immediately')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const createTenant=async()=>{if(!form.id)return setError(ar?'احفظ الشركة أولاً':'Save company first');setBusy(true);setError('');try{const x=await createOrLinkTenantFromLibrary(form.id);setTenant(x);setBundle(await loadMedicalRelationshipBundle(x.organization_id));setOk(ar?'تم إنشاء/ربط الشركة بالـTenant الطبي':'Medical tenant linked')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="facility-module"><div className="page-head"><div><h1>{ar?'الإدراج الذكي لشركات الصيانة الطبية':'Medical Smart Onboarding'}</h1><p className="muted">{ar?'مكتبة طبية أولاً ← AI Assist ← شعار ← Tenant ← علاقات':'Medical library first → AI Assist → Logo → Tenant → Relationships'}</p></div></div>{error&&<div className="alert error">{error}</div>}{ok&&<div className="alert success">{ok}</div>}
 <div className="facility-panel"><h2>{ar?'1. البحث في المكتبة الطبية':'1. Search Medical Library'}</h2><div style={{display:'flex',gap:10}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'اسم الشركة':'Company name'}/><button className="btn secondary" onClick={search}>{ar?'بحث':'Search'}</button></div>{results.map(r=><div key={r.id} className="facility-panel" style={{marginTop:10}}><div className="page-head"><div style={{display:'flex',gap:12,alignItems:'center'}}>{r.logo_url?<img src={r.logo_url} alt="" style={{width:56,height:56,objectFit:'contain'}}/>:null}<div><strong>{r.name_ar||r.name_en}</strong><div className="muted">{r.website||''}</div></div></div><button className="btn xs secondary" onClick={()=>pick(r)}>{ar?'استخدام الموجود':'Use existing'}</button></div></div>)}</div>
 <div className="facility-panel"><h2>{ar?'2. بيانات الشركة':'2. Company Data'}</h2><form onSubmit={save}><div className="form-grid"><label>{ar?'الاسم العربي':'Arabic name'}<input value={form.name_ar} onChange={e=>setForm(v=>({...v,name_ar:e.target.value}))}/></label><label>{ar?'الاسم الإنجليزي':'English name'}<input value={form.name_en} onChange={e=>setForm(v=>({...v,name_en:e.target.value}))}/></label><label>{ar?'الموقع':'Website'}<input value={form.website} onChange={e=>setForm(v=>({...v,website:e.target.value}))}/></label><label>{ar?'البريد':'Email'}<input value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/></label><label>{ar?'الهاتف':'Phone'}<input value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/></label><label>{ar?'المدينة':'City'}<input value={form.city} onChange={e=>setForm(v=>({...v,city:e.target.value}))}/></label><label>{ar?'السجل التجاري':'Registration'}<input value={form.registration_no} onChange={e=>setForm(v=>({...v,registration_no:e.target.value}))}/></label><label>{ar?'الرقم الضريبي':'VAT'}<input value={form.vat_no} onChange={e=>setForm(v=>({...v,vat_no:e.target.value}))}/></label><label className="span-2">{ar?'العنوان':'Address'}<input value={form.address} onChange={e=>setForm(v=>({...v,address:e.target.value}))}/></label><label className="span-2">{ar?'رابط الشعار':'Logo URL'}<input value={form.logo_url} onChange={e=>setForm(v=>({...v,logo_url:e.target.value,logo_source:'manual_url'}))}/></label></div><div className="form-actions"><button type="button" className="btn secondary" disabled={busy} onClick={ai}>AI Assist</button><button className="btn primary" disabled={busy}>{ar?'حفظ في المكتبة':'Save to Medical Library'}</button></div></form>{form.logo_url&&<img src={form.logo_url} alt="" style={{maxWidth:180,maxHeight:80,objectFit:'contain',marginTop:12}}/>}</div>
 <div className="facility-panel"><h2>{ar?'3. إنشاء/ربط شركة الصيانة':'3. Create / Link Tenant'}</h2><button className="btn primary" onClick={createTenant} disabled={busy||!form.id}>{ar?'إنشاء أو ربط Tenant':'Create or Link Tenant'}</button>{tenant&&<div style={{marginTop:12}}><strong>{tenant.name_ar||tenant.name_en}</strong><div className="muted">{tenant.organization_id}</div></div>}</div>
 {tenant&&<div className="facility-panel"><h2>{ar?'4. العلاقات الطبية':'4. Medical Relationships'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12}}><div className="kpi-card"><b>{ar?'الملاك':'Owners'}</b><strong>{bundle.clients?.length||0}</strong></div><div className="kpi-card"><b>{ar?'المواقع':'Sites'}</b><strong>{bundle.sites?.length||0}</strong></div><div className="kpi-card"><b>{ar?'المشاريع':'Projects'}</b><strong>{bundle.projects?.length||0}</strong></div><div className="kpi-card"><b>{ar?'الأجهزة':'Assets'}</b><strong>{bundle.assets?.length||0}</strong></div></div></div>}
 </section>
}
